USE [TaskMeroYatra]
GO

/****** Object:  Table [dbo].[TBL_Menu]    Script Date: 2/16/2021 11:56:30 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TBL_Menu](
	[MenuId] [INT] IDENTITY(1,1) NOT NULL,
	[ParentMenu] [NVARCHAR](100) NOT NULL,
	[Menu] [NVARCHAR](100) NOT NULL,
	[URL] [NVARCHAR](MAX) NOT NULL,
	[IsActive] [BIT] NOT NULL,
	[CreatedBy] [NVARCHAR](100) NOT NULL,
	[CreatedDate] [DATETIME] NOT NULL,
	[Icon] [NVARCHAR](100) NULL,
PRIMARY KEY CLUSTERED 
(
	[MenuId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[TBL_Menu] ADD  DEFAULT ((1)) FOR [IsActive]
GO

ALTER TABLE [dbo].[TBL_Menu] ADD  DEFAULT ('System') FOR [CreatedBy]
GO

ALTER TABLE [dbo].[TBL_Menu] ADD  DEFAULT (GETDATE()) FOR [CreatedDate]
GO


ALTER TABLE dbo.TBL_Menu
ALTER COLUMN Icon NVARCHAR(100) NULL

