CREATE TABLE Tbl_MenuPermission(
PermissionId INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
FK_RoleId INT FOREIGN KEY REFERENCES tblRoleSetup(RoleId) NOT NULL,
FK_MenuId INT FOREIGN KEY REFERENCES TBL_Menu(MenuId) NOT NULL
);




