CREATE TABLE TBL_Menu(
MenuId INT IDENTITY(1,1) NOT NULL,
ParentMenu NVARCHAR(100) NOT NULL,
Menu NVARCHAR(100) NOT NULL,
[URL] NVARCHAR(MAX) NOT NULL,
IsActive BIT DEFAULT(1)NOT NULL,
CreatedBy NVARCHAR(100) DEFAULT('System') NOT NULL,
CreatedDate DATETIME DEFAULT(GETDATE()) NOT NULL
) 
