CREATE TABLE TBL_SPRINT(
 RowId BIGINT IDENTITY(1,1) NOT NULL,
 SprintId INT PRIMARY KEY,
 SprintName NVARCHAR(100) NOT NULL,
 SprintStatus BIT NOT NULL,
 StartedDate DATETIME NOT NULL,
 EndDate DATETIME NOT NULL,
);