USE [TaskMeroYatra]
GO

/****** Object:  Table [dbo].[tblTaskSequence]    Script Date: 2/21/2021 4:10:30 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[tblTaskSequence](
	[RowID] [int] IDENTITY(1,1) NOT NULL,
	[TaskSequence] [bigint] NULL,
PRIMARY KEY CLUSTERED 
(
	[RowID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


