CREATE DATABASE LOGIN_USER

CREATE TABLE TBL_USERS(
ID INT IDENTITY(1,1),
UserName NVARCHAR(255) NOT NULL,
Email NVARCHAR(255) NOT NULL,
[Password] NVARCHAR(255) NOT NULL
)
GO


select * from TBL_USERS

