CREATE TABLE [dbo].[TBL_USERS](
[ID] [INT] IDENTITY(1,1) NOT NULL,
[FullName] [VARCHAR](150) NOT NULL,
[UserName] [NVARCHAR](255) NOT NULL,
[Email] [NVARCHAR](255) NOT NULL,
[PhoneNo] [NVARCHAR](10) NOT NULL,
[Password] [NVARCHAR](255) NOT NULL,
[CreatedDate] [DATETIME] NULL,
[ModifiedDate] [DATETIME] NULL,
[AdminRight] [VARCHAR](10) NULL,
[isActive] [BIT] NULL,
[CreatedBy] [NVARCHAR](100) NULL
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[TBL_USERS] ADD CONSTRAINT [df_AdminRight] DEFAULT ('false') FOR [AdminRight]
GO

ALTER TABLE [dbo].[TBL_USERS] ADD DEFAULT ('1') FOR [isActive]
GO