CREATE DATABASE TaskMeroYatra 

CREATE TABLE TBL_USERS(
ID INT IDENTITY(1,1),
FullName VARCHAR(150) NOT NULL,
UserName NVARCHAR(255) NOT NULL,
Email NVARCHAR(255) NOT NULL,
PhoneNo NVARCHAR(10) NOT NULL,
[Password] NVARCHAR(255) NOT NULL,
CreatedDate DATETIME	NULL,
ModifiedDate DATETIME NULL,

)
GO



ALTER TABLE dbo.TBL_USERS ADD AdminRight BIT NULL DEFAULT '0' 

